const doctors = [
  {
    id: 0,
    name: "Dr. Stan Smith",
    specialization: "Cardiology",
    availability: "Mon-Fri 9am - 6pm",
  },
  {
    id: 1,
    name: "Dr. Emily Johnson",
    specialization: "Pediatrics",
    availability: "Tues-Sat 8am - 4pm",
  },
  {
    id: 2,
    name: "Dr. Jasmine Patel",
    specialization: "Dermatology",
    availability: "Mon-Fri 10am - 7pm",
  },
  {
    id: 3,
    name: "Dr. Michael Chang",
    specialization: "Orthopedics",
    availability: "Wed-Sun 11am - 8pm",
  },
  {
    id: 4,
    name: "Dr. Sarah Rodriguez",
    specialization: "Ophthalmology",
    availability: "Mon-Thu 8:30am - 5:30pm, Fri 8:30am - 2pm",
  },
  {
    id: 5,
    name: "Dr. Robert Turner",
    specialization: "Neurology",
    availability: "Tue-Sat 10am - 6pm",
  },
  {
    id: 6,
    name: "Dr. Alicia Ramirez",
    specialization: "Gastroenterology",
    availability: "Mon-Fri 9am - 5pm",
  },
  {
    id: 7,
    name: "Dr. Christopher Anderson",
    specialization: "Pulmonology",
    availability: "Wed-Sun 12pm - 9pm",
  },
  {
    id: 8,
    name: "Dr. Michelle Lee",
    specialization: "Rheumatology",
    availability: "Mon-Thu 10am - 6pm, Sat 9am - 3pm",
  },
  {
    id: 9,
    name: "Dr. Daniel Garcia",
    specialization: "Endocrinology",
    availability: "Tue-Fri 8:30am - 4:30pm",
  },
  {
    id: 10,
    name: "Dr. Samantha Miller",
    specialization: "Hematology",
    availability: "Mon-Sat 9am - 5pm",
  },
  {
    id: 11,
    name: "Dr. Jonathan Carter",
    specialization: "Urology",
    availability: "Tue-Fri 10am - 7pm, Sat 9am - 2pm",
  },
  {
    id: 12,
    name: "Dr. Erica Taylor",
    specialization: "Psychiatry",
    availability: "Mon-Thu 11am - 8pm, Fri 9am - 5pm",
  },
  {
    id: 13,
    name: "Dr. Andrew Walker",
    specialization: "Allergy and Immunology",
    availability: "Wed-Sun 1pm - 9pm",
  },
  {
    id: 14,
    name: "Dr. Olivia Martinez",
    specialization: "Nephrology",
    availability: "Mon-Fri 9:30am - 6:30pm",
  },
  {
    id: 15,
    name: "Dr. Brian Turner",
    specialization: "Infectious Diseases",
    availability: "Tue-Sat 10am - 7pm",
  },
  {
    id: 16,
    name: "Dr. Vanessa Rodriguez",
    specialization: "Gynecology",
    availability: "Mon-Fri 8:30am - 5:30pm",
  },
  {
    id: 17,
    name: "Dr. Nicholas Turner",
    specialization: "Rheumatology",
    availability: "Tue-Thu 9am - 6pm, Sat 10am - 4pm",
  },
  {
    id: 18,
    name: "Dr. Maya Patel",
    specialization: "Geriatrics",
    availability: "Mon-Wed 10am - 6pm, Fri 9am - 3pm",
  },
  {
    id: 19,
    name: "Dr. Jordan Anderson",
    specialization: "Gastroenterology",
    availability: "Thu-Sun 11am - 8pm",
  },
  {
    id: 20,
    name: "Dr. Taylor Lewis",
    specialization: "Dentistry",
    availability: "Mon-Fri 8am - 4pm",
  },
  {
    id: 21,
    name: "Dr. Olivia White",
    specialization: "Oncology",
    availability: "Tue-Sat 9am - 6pm",
  },
  {
    id: 22,
    name: "Dr. Ethan Adams",
    specialization: "Cardiac Surgery",
    availability: "Mon-Thu 10am - 7pm, Sat 9am - 3pm",
  },
  {
    id: 23,
    name: "Dr. Sophia Taylor",
    specialization: "Plastic Surgery",
    availability: "Tue-Fri 9:30am - 6:30pm",
  },
  {
    id: 24,
    name: "Dr. James Baker",
    specialization: "Obstetrics",
    availability: "Wed-Sun 8am - 5pm",
  },
  {
    id: 25,
    name: "Dr. Natalie Clark",
    specialization: "Neonatology",
    availability: "Mon-Fri 8am - 4pm",
  },
  {
    id: 26,
    name: "Dr. Benjamin Turner",
    specialization: "Hepatology",
    availability: "Thu-Sun 10am - 7pm",
  },
  {
    id: 27,
    name: "Dr. Isabella Martinez",
    specialization: "Pulmonary Medicine",
    availability: "Tue-Sat 11am - 8pm",
  },
  {
    id: 28,
    name: "Dr. Noah Adams",
    specialization: "Sports Medicine",
    availability: "Mon-Thu 9am - 6pm, Sat 10am - 4pm",
  },
  {
    id: 29,
    name: "Dr. Gabriella White",
    specialization: "Allergology",
    availability: "Wed-Sun 9am - 5pm",
  },
  {
    id: 30,
    name: "Dr. Oliver Taylor",
    specialization: "Nuclear Medicine",
    availability: "Mon-Fri 10am - 7pm",
  },
  {
    id: 31,
    name: "Dr. Lily Garcia",
    specialization: "Dental Surgery",
    availability: "Tue-Sat 8am - 4pm",
  },
  {
    id: 32,
    name: "Dr. Aiden Lewis",
    specialization: "Vascular Surgery",
    availability: "Mon-Thu 8:30am - 5:30pm, Sat 9am - 2pm",
  },
  {
    id: 33,
    name: "Dr. Ava Turner",
    specialization: "Hematology-Oncology",
    availability: "Wed-Sun 12pm - 9pm",
  },
  {
    id: 34,
    name: "Dr. Logan Martinez",
    specialization: "Geriatric Psychiatry",
    availability: "Mon-Fri 9am - 5pm",
  },
  {
    id: 35,
    name: "Dr. Zoey Clark",
    specialization: "Rheumatoid Arthritis",
    availability: "Tue-Sat 10am - 7pm",
  },
  {
    id: 36,
    name: "Dr. Elijah Taylor",
    specialization: "Podiatry",
    availability: "Mon-Thu 8am - 4pm",
  },
  {
    id: 37,
    name: "Dr. Sophia Rodriguez",
    specialization: "Cardiology",
    availability: "Mon-Fri 10am - 7pm, Sat 9am - 3pm",
  },
  {
    id: 38,
    name: "Dr. Mason Adams",
    specialization: "Orthopedics",
    availability: "Tue-Sat 11am - 8pm",
  },
  {
    id: 39,
    name: "Dr. Ava Turner",
    specialization: "Gastroenterology",
    availability: "Wed-Sun 9am - 5pm",
  },
  {
    id: 40,
    name: "Dr. Liam Martinez",
    specialization: "Cardiology",
    availability: "Mon-Fri 9am - 5pm",
  },
  {
    id: 41,
    name: "Dr. Zoe Clark",
    specialization: "Orthopedics",
    availability: "Tue-Sat 10am - 6pm",
  },
  {
    id: 42,
    name: "Dr. Noah White",
    specialization: "Dermatology",
    availability: "Mon-Fri 8:30am - 5:30pm",
  },
  {
    id: 43,
    name: "Dr. Harper Taylor",
    specialization: "Gastroenterology",
    availability: "Thu-Sun 11am - 8pm",
  },
  {
    id: 44,
    name: "Dr. Oliver Garcia",
    specialization: "Dermatology",
    availability: "Mon-Thu 9am - 6pm, Sat 10am - 4pm",
  },
  {
    id: 45,
    name: "Dr. Isabella Turner",
    specialization: "Neurology",
    availability: "Tue-Fri 10am - 7pm",
  },
  {
    id: 46,
    name: "Dr. Elijah Adams",
    specialization: "Neurology",
    availability: "Mon-Wed 8am - 4pm, Fri 9am - 5pm",
  },
  {
    id: 47,
    name: "Dr. Mia Rodriguez",
    specialization: "Neurology",
    availability: "Mon-Fri 10am - 7pm",
  },
  {
    id: 48,
    name: "Dr. Caleb Turner",
    specialization: "Neurology",
    availability: "Tue-Sat 9am - 6pm",
  },
  {
    id: 49,
    name: "Dr. Addison Martinez",
    specialization: "Neurology",
    availability: "Wed-Sun 11am - 8pm",
  },
];

module.exports = { doctors };
